<?xml version="1.0" encoding="utf-8"?><Database Name="EmailImport" Class="EmailImportDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local);Initial Catalog=EmailImport;Integrated Security=True" SettingsObjectName="EmailImport.Configuration.Properties.Settings" SettingsPropertyName="EmailImportConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Mailboxes" Member="Mailboxes">
    <Type Name="Mailbox">
      <Column Name="MailboxGUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProfileObject" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CodeSnippets" Member="CodeSnippets">
    <Type Name="CodeSnippet">
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Settings" Member="Settings">
    <Type Name="Setting">
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
    </Type>
  </Table>
</Database>