//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailImport.Configuration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmailImport.Configuration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using Aspose.Email.Mail;
        ///
        /////
        ///// Host Objects:
        /////
        ///// Message       - (Aspose.Email.Mail.MailMessage)
        ///// IgnoreMessage - (System.Boolean)
        /////
        ///
        ///private void MailMessage_Loaded()
        ///{
        ///    //
        ///    // TODO: Add Code
        ///    //
        ///}.
        /// </summary>
        internal static string DefaultScript {
            get {
                return ResourceManager.GetString("DefaultScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decipha IT Support &lt;itsupport@decipha.com.au&gt;.
        /// </summary>
        internal static string DefaultTemplateBcc {
            get {
                return ResourceManager.GetString("DefaultTemplateBcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;HTML&gt;&lt;HEAD&gt;&lt;/HEAD&gt;
        ///&lt;BODY lang=EN-AU contentEditable=true style=&quot;tab-interval: 36.0pt&quot; scroll=auto link=blue vLink=purple&gt;
        ///&lt;DIV class=WordSection1&gt;
        ///&lt;P class=MsoNormal&gt;&lt;FONT face=Calibri&gt;Thank you for your email.&lt;/FONT&gt;&lt;/P&gt;
        ///&lt;P class=MsoNormal&gt;&lt;FONT face=Calibri&gt;Unfortunately the email received could not be processed by Decipha for the following reasons:&lt;/FONT&gt;&lt;/P&gt;
        ///&lt;TABLE class=MsoTableGrid style=&quot;BORDER-TOP: medium none; BORDER-RIGHT: medium none; BORDER-COLLAPSE: collapse; BORDER-BOTTOM: medium none; B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultTemplateBody {
            get {
                return ResourceManager.GetString("DefaultTemplateBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decipha Email Import &lt;noreply@decipha.com.au&gt;.
        /// </summary>
        internal static string DefaultTemplateFrom {
            get {
                return ResourceManager.GetString("DefaultTemplateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process email....
        /// </summary>
        internal static string DefaultTemplateSubject {
            get {
                return ResourceManager.GetString("DefaultTemplateSubject", resourceCulture);
            }
        }
    }
}
